id: IF7F1A77F
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-08-16T14:22:52.028023'
last_modified: '2022-08-16T14:22:52.028033'
parser: null
source_metadata:
  title: 'Śāntideva: Bodhicaryāvatāra'
  language: en
  base:
    E38A:
      base_file: E38A.txt
      order: 1
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
